// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQwaqlQFCTV4tYyBdJodvjAvSBVIHu49g',
    appId: '1:807008729966:web:6ca7fbc20ea46bd4d79f7f',
    messagingSenderId: '807008729966',
    projectId: 'news-api-ef6bb',
    authDomain: 'news-api-ef6bb.firebaseapp.com',
    databaseURL: 'https://news-api-ef6bb-default-rtdb.firebaseio.com',
    storageBucket: 'news-api-ef6bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1VRduCkzcpkdFusnyDvjm8k0HBzUyEY',
    appId: '1:807008729966:android:5c39fb4c4f4c0663d79f7f',
    messagingSenderId: '807008729966',
    projectId: 'news-api-ef6bb',
    databaseURL: 'https://news-api-ef6bb-default-rtdb.firebaseio.com',
    storageBucket: 'news-api-ef6bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKd5K9nY0xH0ky3p1TtHL4TQWrhsoMP58',
    appId: '1:807008729966:ios:f59f514f0b190cccd79f7f',
    messagingSenderId: '807008729966',
    projectId: 'news-api-ef6bb',
    databaseURL: 'https://news-api-ef6bb-default-rtdb.firebaseio.com',
    storageBucket: 'news-api-ef6bb.appspot.com',
    iosClientId: '807008729966-4lbbd78hr4anb6ikobv7lafev6nvnj42.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppApiCubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKd5K9nY0xH0ky3p1TtHL4TQWrhsoMP58',
    appId: '1:807008729966:ios:78581d584f164fecd79f7f',
    messagingSenderId: '807008729966',
    projectId: 'news-api-ef6bb',
    databaseURL: 'https://news-api-ef6bb-default-rtdb.firebaseio.com',
    storageBucket: 'news-api-ef6bb.appspot.com',
    iosClientId: '807008729966-abmnt719fjns8p5sml74ggl59qlbd7d1.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppApiCubit.RunnerTests',
  );
}
